/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package chat.client;


public class Client {
    public static void main(String[] args) {
        System.out.println("This is Client");
    }
}
